services:
  backend:
    build: .
    container_name: backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/mysqldb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      FRONTEND_URL: https://ee188ed0a9da359d452af4080bb4cea2.serveo.net
    depends_on:
      db:
        condition: service_healthy # Wait for DB container to start
    ports:
      - "8080:8080"  # Expose backend on host port 8080
    networks:
      - internal  # Backend connects only to internal network (not exposed externally)
    restart: unless-stopped  # Restart policy to keep container running unless stopped manually
    logging:
      driver: json-file  # Limit log file size and rotation to avoid disk bloat
      options:
        max-size: "10m"
        max-file: "3"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    environment:
      VITE_BACKEND_URL: https://5fb32d1bd96c47ec00788c08c6aa94ec.serveo.net
      VITE_FRONTEND_URL: https://ee188ed0a9da359d452af4080bb4cea2.serveo.net
    ports:
      - "80:80" #for PROD (Http only)
    depends_on:
      - backend  # Wait for backend container to start
    networks:
      - internal  # Agregado para que frontend pueda llamar al backend por nombre de servicio
      - frontend_net  # Also connected to frontend_net to expose frontend externally
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  db:
    image: mysql:latest
    container_name: mysql
    environment:
      # Credentials and DB name for MySQL (development generic values)
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysqldb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql  # Persist DB data across container restarts
    networks:
      - internal  # DB only accessible inside internal network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 5s
      retries: 10

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  db_data:  # Volume for persistent MySQL data

networks:
  internal:
    driver: bridge  # Internal network for backend and db communication only
  frontend_net:
    driver: bridge  # Network to expose frontend externally
